/**
 * Manifest of all available Kaitai Struct format definitions.
 * This file is auto-generated by sync-ksy.js - do not edit manually.
 */

export type ManifestEntry =
  | {
      name: string;
      title: string;
      path: string;
    }
  | {
      name: string;
      children: ManifestEntry[];
    };

export const manifest = [
    {
      name: "3d",
      children: [
        {
          name: "gltf_binary",
          title: "GL Transmission Format, binary container",
          path: "3d/gltf_binary.ksy",
        }
      ],
    },
    {
      name: "archive",
      children: [
        {
          name: "android_bootldr_asus",
          title: "ASUS Fugu bootloader.img format (version 2 and later)",
          path: "archive/android_bootldr_asus.ksy",
        },
        {
          name: "android_bootldr_huawei",
          title: "Huawei Bootloader packed image format",
          path: "archive/android_bootldr_huawei.ksy",
        },
        {
          name: "android_bootldr_qcom",
          title: "Qualcomm Snapdragon (MSM) bootloader.img format",
          path: "archive/android_bootldr_qcom.ksy",
        },
        {
          name: "android_dto",
          title: "Android DTB/DTBO Partition",
          path: "archive/android_dto.ksy",
        },
        {
          name: "android_img",
          title: "Android Boot Image",
          path: "archive/android_img.ksy",
        },
        {
          name: "android_sparse",
          title: "Android sparse image",
          path: "archive/android_sparse.ksy",
        },
        {
          name: "cpio_old_le",
          title: "cpio archive, old binary variant, little-endian",
          path: "archive/cpio_old_le.ksy",
        },
        {
          name: "gzip",
          title: "gzip",
          path: "archive/gzip.ksy",
        },
        {
          name: "lzh",
          title: "lzh",
          path: "archive/lzh.ksy",
        },
        {
          name: "mozilla_mar",
          title: "Mozilla ARchive",
          path: "archive/mozilla_mar.ksy",
        },
        {
          name: "phar_without_stub",
          title: "PHP phar archive (without stub)",
          path: "archive/phar_without_stub.ksy",
        },
        {
          name: "rar",
          title: "RAR (Roshall ARchiver) archive files",
          path: "archive/rar.ksy",
        },
        {
          name: "respack",
          title: "ResPack",
          path: "archive/respack.ksy",
        },
        {
          name: "rpm",
          title: "RPM package file",
          path: "archive/rpm.ksy",
        },
        {
          name: "xar",
          title: "XAR (eXtensible ARchive)",
          path: "archive/xar.ksy",
        },
        {
          name: "zip",
          title: "ZIP archive file",
          path: "archive/zip.ksy",
        },
        {
          name: "zisofs",
          title: "zisofs",
          path: "archive/zisofs.ksy",
        }
      ],
    },
    {
      name: "cad",
      children: [
        {
          name: "monomakh_sapr_chg",
          title: "monomakh_sapr_chg",
          path: "cad/monomakh_sapr_chg.ksy",
        }
      ],
    },
    {
      name: "common",
      children: [
        {
          name: "bcd",
          title: "BCD (Binary Coded Decimals)",
          path: "common/bcd.ksy",
        },
        {
          name: "bytes_with_io",
          title: "Byte array with an `_io` member",
          path: "common/bytes_with_io.ksy",
        },
        {
          name: "dos_datetime",
          title: "MS-DOS datetime",
          path: "common/dos_datetime.ksy",
        },
        {
          name: "riff",
          title: "Resource Interchange File Format (RIFF)",
          path: "common/riff.ksy",
        },
        {
          name: "utf8_string",
          title: "UTF-8-encoded string",
          path: "common/utf8_string.ksy",
        },
        {
          name: "vlq_base128_be",
          title: "Variable length quantity, unsigned integer, base128, big-endian",
          path: "common/vlq_base128_be.ksy",
        },
        {
          name: "vlq_base128_le",
          title: "Variable length quantity, unsigned/signed integer, base128, little-endian",
          path: "common/vlq_base128_le.ksy",
        }
      ],
    },
    {
      name: "database",
      children: [
        {
          name: "dbf",
          title: "dbf",
          path: "database/dbf.ksy",
        },
        {
          name: "gettext_mo",
          title: "gettext binary database",
          path: "database/gettext_mo.ksy",
        },
        {
          name: "sqlite3",
          title: "SQLite3 database file",
          path: "database/sqlite3.ksy",
        },
        {
          name: "tsm",
          title: "InfluxDB TSM file",
          path: "database/tsm.ksy",
        }
      ],
    },
    {
      name: "executable",
      children: [
        {
          name: "android_nanoapp_header",
          title: "Android nanoapp header",
          path: "executable/android_nanoapp_header.ksy",
        },
        {
          name: "dex",
          title: "Android Dalvik VM executable (dex)",
          path: "executable/dex.ksy",
        },
        {
          name: "dos_mz",
          title: "DOS MZ executable",
          path: "executable/dos_mz.ksy",
        },
        {
          name: "elf",
          title: "Executable and Linkable Format",
          path: "executable/elf.ksy",
        },
        {
          name: "java_class",
          title: "java_class",
          path: "executable/java_class.ksy",
        },
        {
          name: "mach_o",
          title: "mach_o",
          path: "executable/mach_o.ksy",
        },
        {
          name: "mach_o_fat",
          title: "macOS Mach-O multiarch (\"fat\") binary",
          path: "executable/mach_o_fat.ksy",
        },
        {
          name: "microsoft_pe",
          title: "Microsoft PE (Portable Executable) file format",
          path: "executable/microsoft_pe.ksy",
        },
        {
          name: "python_pyc_27",
          title: "python_pyc_27",
          path: "executable/python_pyc_27.ksy",
        },
        {
          name: "swf",
          title: "Adobe Flash (AKA Shockwave Flash, Macromedia Flash)",
          path: "executable/swf.ksy",
        },
        {
          name: "uefi_te",
          title: "TE (Terse Executable) file",
          path: "executable/uefi_te.ksy",
        }
      ],
    },
    {
      name: "filesystem",
      children: [
        {
          name: "amlogic_emmc_partitions",
          title: "Amlogic proprietary eMMC partition table",
          path: "filesystem/amlogic_emmc_partitions.ksy",
        },
        {
          name: "android_super",
          title: "Android Dynamic Partitions metadata",
          path: "filesystem/android_super.ksy",
        },
        {
          name: "apm_partition_table",
          title: "APM (Apple Partition Map) partition table",
          path: "filesystem/apm_partition_table.ksy",
        },
        {
          name: "apple_single_double",
          title: "AppleSingle / AppleDouble",
          path: "filesystem/apple_single_double.ksy",
        },
        {
          name: "btrfs_stream",
          title: "btrfs_stream",
          path: "filesystem/btrfs_stream.ksy",
        },
        {
          name: "cramfs",
          title: "cramfs",
          path: "filesystem/cramfs.ksy",
        },
        {
          name: "ext2",
          title: "ext2 filesystem",
          path: "filesystem/ext2.ksy",
        },
        {
          name: "gpt_partition_table",
          title: "GPT (GUID) partition table",
          path: "filesystem/gpt_partition_table.ksy",
        },
        {
          name: "iso9660",
          title: "ISO9660 CD filesystem",
          path: "filesystem/iso9660.ksy",
        },
        {
          name: "luks",
          title: "Linux Unified Key Setup",
          path: "filesystem/luks.ksy",
        },
        {
          name: "lvm2",
          title: "Logical Volume Manager version 2",
          path: "filesystem/lvm2.ksy",
        },
        {
          name: "mbr_partition_table",
          title: "MBR (Master Boot Record) partition table",
          path: "filesystem/mbr_partition_table.ksy",
        },
        {
          name: "tr_dos_image",
          title: "TR-DOS flat-file disk image",
          path: "filesystem/tr_dos_image.ksy",
        },
        {
          name: "vdi",
          title: "VirtualBox Disk Image",
          path: "filesystem/vdi.ksy",
        },
        {
          name: "vfat",
          title: "vfat",
          path: "filesystem/vfat.ksy",
        },
        {
          name: "vmware_vmdk",
          title: "VMWare Virtual Disk",
          path: "filesystem/vmware_vmdk.ksy",
        },
        {
          name: "zx_spectrum_tap",
          title: "ZX Spectrum tape file",
          path: "filesystem/zx_spectrum_tap.ksy",
        }
      ],
    },
    {
      name: "firmware",
      children: [
        {
          name: "andes_firmware",
          title: "Andes Firmware Image layout as seen in MT76 Wifi Chipsets",
          path: "firmware/andes_firmware.ksy",
        },
        {
          name: "broadcom_trx",
          title: "Broadcom devices .trx firmware packaging",
          path: "firmware/broadcom_trx.ksy",
        },
        {
          name: "ines",
          title: "ines",
          path: "firmware/ines.ksy",
        },
        {
          name: "uimage",
          title: "U-Boot Image wrapper",
          path: "firmware/uimage.ksy",
        }
      ],
    },
    {
      name: "font",
      children: [
        {
          name: "grub2_font",
          title: "GRUB 2 font",
          path: "font/grub2_font.ksy",
        },
        {
          name: "pcf_font",
          title: "Portable Compiled Format (PCF) font",
          path: "font/pcf_font.ksy",
        },
        {
          name: "ttf",
          title: "TrueType Font File",
          path: "font/ttf.ksy",
        }
      ],
    },
    {
      name: "game",
      children: [
        {
          name: "allegro_dat",
          title: "Allegro data file",
          path: "game/allegro_dat.ksy",
        },
        {
          name: "doom_wad",
          title: "doom_wad",
          path: "game/doom_wad.ksy",
        },
        {
          name: "dune_2_pak",
          title: "dune_2_pak",
          path: "game/dune_2_pak.ksy",
        },
        {
          name: "fallout_dat",
          title: "fallout_dat",
          path: "game/fallout_dat.ksy",
        },
        {
          name: "fallout2_dat",
          title: "fallout2_dat",
          path: "game/fallout2_dat.ksy",
        },
        {
          name: "ftl_dat",
          title: "ftl_dat",
          path: "game/ftl_dat.ksy",
        },
        {
          name: "gran_turismo_vol",
          title: "Gran Turismo File System (GTFS)",
          path: "game/gran_turismo_vol.ksy",
        },
        {
          name: "heaps_pak",
          title: "heaps_pak",
          path: "game/heaps_pak.ksy",
        },
        {
          name: "heroes_of_might_and_magic_agg",
          title: "heroes_of_might_and_magic_agg",
          path: "game/heroes_of_might_and_magic_agg.ksy",
        },
        {
          name: "heroes_of_might_and_magic_bmp",
          title: "heroes_of_might_and_magic_bmp",
          path: "game/heroes_of_might_and_magic_bmp.ksy",
        },
        {
          name: "minecraft_nbt",
          title: "Minecraft NBT (Named Binary Tag)",
          path: "game/minecraft_nbt.ksy",
        },
        {
          name: "quake_mdl",
          title: "Quake 1 (idtech2) model format (MDL version 6)",
          path: "game/quake_mdl.ksy",
        },
        {
          name: "quake_pak",
          title: "quake_pak",
          path: "game/quake_pak.ksy",
        },
        {
          name: "quake2_md2",
          title: "Quake II player model (version 8)",
          path: "game/quake2_md2.ksy",
        },
        {
          name: "renderware_binary_stream",
          title: "RenderWare binary stream",
          path: "game/renderware_binary_stream.ksy",
        },
        {
          name: "saints_row_2_vpp_pc",
          title: "Saints Rows 2 game packages",
          path: "game/saints_row_2_vpp_pc.ksy",
        },
        {
          name: "warcraft_2_pud",
          title: "Warcraft II map files",
          path: "game/warcraft_2_pud.ksy",
        }
      ],
    },
    {
      name: "geospatial",
      children: [
        {
          name: "shapefile_index",
          title: "Shapefile index file",
          path: "geospatial/shapefile_index.ksy",
        },
        {
          name: "shapefile_main",
          title: "Shapefile main file",
          path: "geospatial/shapefile_main.ksy",
        }
      ],
    },
    {
      name: "hardware",
      children: [
        {
          name: "dtb",
          title: "Flattened Devicetree Format",
          path: "hardware/dtb.ksy",
        },
        {
          name: "edid",
          title: "EDID (VESA Enhanced Extended Display Identification Data)",
          path: "hardware/edid.ksy",
        },
        {
          name: "mifare",
          children: [
            {
              name: "mifare_classic",
              title: "Mifare Classic RFID tag dump",
              path: "hardware/mifare/mifare_classic.ksy",
            }
          ],
        }
      ],
    },
    {
      name: "image",
      children: [
        {
          name: "bmp",
          title: "bmp",
          path: "image/bmp.ksy",
        },
        {
          name: "dicom",
          title: "Digital Imaging and Communications in Medicine (DICOM) file format",
          path: "image/dicom.ksy",
        },
        {
          name: "exif",
          title: "exif",
          path: "image/exif.ksy",
        },
        {
          name: "gif",
          title: "GIF (Graphics Interchange Format) image file",
          path: "image/gif.ksy",
        },
        {
          name: "gimp_brush",
          title: "GIMP brush file version 2",
          path: "image/gimp_brush.ksy",
        },
        {
          name: "icc_4",
          title: "ICC profile, version 4",
          path: "image/icc_4.ksy",
        },
        {
          name: "ico",
          title: "Microsoft Windows icon file",
          path: "image/ico.ksy",
        },
        {
          name: "jpeg",
          title: "JPEG (Joint Photographic Experts Group) File Interchange Format",
          path: "image/jpeg.ksy",
        },
        {
          name: "nitf",
          title: "National Imagery Transmission Format",
          path: "image/nitf.ksy",
        },
        {
          name: "pcx",
          title: "pcx",
          path: "image/pcx.ksy",
        },
        {
          name: "pcx_dcx",
          title: "pcx_dcx",
          path: "image/pcx_dcx.ksy",
        },
        {
          name: "pif",
          title: "Portable Image Format",
          path: "image/pif.ksy",
        },
        {
          name: "png",
          title: "PNG (Portable Network Graphics) file",
          path: "image/png.ksy",
        },
        {
          name: "psx_tim",
          title: "psx_tim",
          path: "image/psx_tim.ksy",
        },
        {
          name: "tga",
          title: "TGA (AKA Truevision TGA, AKA TARGA) raster image file format",
          path: "image/tga.ksy",
        },
        {
          name: "wmf",
          title: "Windows Metafile (WMF) vector image",
          path: "image/wmf.ksy",
        },
        {
          name: "xwd",
          title: "xwd (X Window Dump) bitmap image",
          path: "image/xwd.ksy",
        }
      ],
    },
    {
      name: "log",
      children: [
        {
          name: "aix_utmp",
          title: "utmp log file, IBM AIX version",
          path: "log/aix_utmp.ksy",
        },
        {
          name: "glibc_utmp",
          title: "utmp log file, Linux/glibc version",
          path: "log/glibc_utmp.ksy",
        },
        {
          name: "hashcat_restore",
          title: "Hashcat Restore file",
          path: "log/hashcat_restore.ksy",
        },
        {
          name: "mcap",
          title: "MCAP",
          path: "log/mcap.ksy",
        },
        {
          name: "sudoers_ts",
          title: "Sudoers Time Stamp file",
          path: "log/sudoers_ts.ksy",
        },
        {
          name: "systemd_journal",
          title: "systemd journal file",
          path: "log/systemd_journal.ksy",
        },
        {
          name: "windows_evt_log",
          title: "Windows Event Log (EVT)",
          path: "log/windows_evt_log.ksy",
        }
      ],
    },
    {
      name: "machine_code",
      children: [
        {
          name: "code_6502",
          title: "code_6502",
          path: "machine_code/code_6502.ksy",
        }
      ],
    },
    {
      name: "macos",
      children: [
        {
          name: "compressed_resource",
          title: "Compressed Macintosh resource",
          path: "macos/compressed_resource.ksy",
        },
        {
          name: "ds_store",
          title: "macOS '.DS_Store' format",
          path: "macos/ds_store.ksy",
        },
        {
          name: "mac_os_resource_snd",
          title: "Classic MacOS Sound Resource",
          path: "macos/mac_os_resource_snd.ksy",
        },
        {
          name: "resource_fork",
          title: "Macintosh resource fork data",
          path: "macos/resource_fork.ksy",
        },
        {
          name: "resource_compression",
          children: [
            {
              name: "dcmp_0",
              title: "Compressed Macintosh resource data, Apple `'dcmp' (0)` format",
              path: "macos/resource_compression/dcmp_0.ksy",
            },
            {
              name: "dcmp_1",
              title: "Compressed Macintosh resource data, Apple `'dcmp' (1)` format",
              path: "macos/resource_compression/dcmp_1.ksy",
            },
            {
              name: "dcmp_2",
              title: "Compressed Macintosh resource data, Apple `'dcmp' (2)` format",
              path: "macos/resource_compression/dcmp_2.ksy",
            },
            {
              name: "dcmp_variable_length_integer",
              title: "Variable-length integer used in Apple `'dcmp' (0)` and `'dcmp' (1)` compressed resource formats",
              path: "macos/resource_compression/dcmp_variable_length_integer.ksy",
            }
          ],
        }
      ],
    },
    {
      name: "media",
      children: [
        {
          name: "android_opengl_shaders_cache",
          title: "com.android.opengl.shaders_cache file",
          path: "media/android_opengl_shaders_cache.ksy",
        },
        {
          name: "au",
          title: "AU audio format",
          path: "media/au.ksy",
        },
        {
          name: "avi",
          title: "Microsoft AVI file",
          path: "media/avi.ksy",
        },
        {
          name: "blender_blend",
          title: "blender_blend",
          path: "media/blender_blend.ksy",
        },
        {
          name: "creative_voice_file",
          title: "Creative Voice File",
          path: "media/creative_voice_file.ksy",
        },
        {
          name: "genmidi_op2",
          title: "GENMIDI.OP2 OPL2 sound bank",
          path: "media/genmidi_op2.ksy",
        },
        {
          name: "id3v1_1",
          title: "ID3v1.1 tag for .mp3 files",
          path: "media/id3v1_1.ksy",
        },
        {
          name: "id3v2_3",
          title: "ID3v2.3 tag for .mp3 files",
          path: "media/id3v2_3.ksy",
        },
        {
          name: "id3v2_4",
          title: "ID3v2.4 tag for .mp3 files",
          path: "media/id3v2_4.ksy",
        },
        {
          name: "magicavoxel_vox",
          title: "MagicaVoxel File",
          path: "media/magicavoxel_vox.ksy",
        },
        {
          name: "ogg",
          title: "Ogg media container file",
          path: "media/ogg.ksy",
        },
        {
          name: "quicktime_mov",
          title: "quicktime_mov",
          path: "media/quicktime_mov.ksy",
        },
        {
          name: "standard_midi_file",
          title: "Standard MIDI file",
          path: "media/standard_midi_file.ksy",
        },
        {
          name: "stl",
          title: "stl",
          path: "media/stl.ksy",
        },
        {
          name: "vp8_duck_ivf",
          title: "Duck IVF (container format for VP8)",
          path: "media/vp8_duck_ivf.ksy",
        },
        {
          name: "wav",
          title: "Microsoft WAVE audio file",
          path: "media/wav.ksy",
        },
        {
          name: "tracker_modules",
          children: [
            {
              name: "fasttracker_xm_module",
              title: "Extended Module",
              path: "media/tracker_modules/fasttracker_xm_module.ksy",
            },
            {
              name: "s3m",
              title: "Scream Tracker 3 module",
              path: "media/tracker_modules/s3m.ksy",
            }
          ],
        }
      ],
    },
    {
      name: "network",
      children: [
        {
          name: "bitcoin_transaction",
          title: "Bitcoin Transaction",
          path: "network/bitcoin_transaction.ksy",
        },
        {
          name: "dime_message",
          title: "DIME (Direct Internet Message Encapsulation) Message",
          path: "network/dime_message.ksy",
        },
        {
          name: "dns_packet",
          title: "DNS (Domain Name Service) packet",
          path: "network/dns_packet.ksy",
        },
        {
          name: "ethernet_frame",
          title: "Ethernet frame (layer 2, IEEE 802.3)",
          path: "network/ethernet_frame.ksy",
        },
        {
          name: "hccap",
          title: "Hashcat capture file (old version)",
          path: "network/hccap.ksy",
        },
        {
          name: "hccapx",
          title: "Hashcat capture file",
          path: "network/hccapx.ksy",
        },
        {
          name: "icmp_packet",
          title: "ICMP network packet",
          path: "network/icmp_packet.ksy",
        },
        {
          name: "ipv4_packet",
          title: "IPv4 network packet",
          path: "network/ipv4_packet.ksy",
        },
        {
          name: "ipv6_packet",
          title: "IPv6 network packet",
          path: "network/ipv6_packet.ksy",
        },
        {
          name: "microsoft_network_monitor_v2",
          title: "microsoft_network_monitor_v2",
          path: "network/microsoft_network_monitor_v2.ksy",
        },
        {
          name: "packet_ppi",
          title: "packet_ppi",
          path: "network/packet_ppi.ksy",
        },
        {
          name: "pcap",
          title: "pcap",
          path: "network/pcap.ksy",
        },
        {
          name: "protocol_body",
          title: "protocol_body",
          path: "network/protocol_body.ksy",
        },
        {
          name: "rtcp_payload",
          title: "rtcp network payload (single udp packet)",
          path: "network/rtcp_payload.ksy",
        },
        {
          name: "rtp_packet",
          title: "RTP (Real-time Transport Protocol)",
          path: "network/rtp_packet.ksy",
        },
        {
          name: "rtpdump",
          title: "Rtpdump (rtptools)",
          path: "network/rtpdump.ksy",
        },
        {
          name: "tcp_segment",
          title: "TCP (Transmission Control Protocol) segment",
          path: "network/tcp_segment.ksy",
        },
        {
          name: "tls_client_hello",
          title: "tls_client_hello",
          path: "network/tls_client_hello.ksy",
        },
        {
          name: "udp_datagram",
          title: "UDP (User Datagram Protocol) datagram",
          path: "network/udp_datagram.ksy",
        },
        {
          name: "websocket",
          title: "WebSocket",
          path: "network/websocket.ksy",
        },
        {
          name: "some_ip",
          children: [
            {
              name: "some_ip",
              title: "AUTOSAR SOME/IP",
              path: "network/some_ip/some_ip.ksy",
            },
            {
              name: "some_ip_container",
              title: "AUTOSAR SOME/IP container",
              path: "network/some_ip/some_ip_container.ksy",
            },
            {
              name: "some_ip_sd",
              title: "AUTOSAR SOME/IP Service Discovery",
              path: "network/some_ip/some_ip_sd.ksy",
            },
            {
              name: "some_ip_sd_entries",
              title: "AUTOSAR SOME/IP Service Discovery Entries",
              path: "network/some_ip/some_ip_sd_entries.ksy",
            },
            {
              name: "some_ip_sd_options",
              title: "AUTOSAR SOME/IP Service Discovery Options",
              path: "network/some_ip/some_ip_sd_options.ksy",
            }
          ],
        }
      ],
    },
    {
      name: "scientific",
      children: [
        {
          name: "nt_mdt",
          children: [
            {
              name: "nt_mdt",
              title: "NT-MDT data",
              path: "scientific/nt_mdt/nt_mdt.ksy",
            },
            {
              name: "nt_mdt_pal",
              title: "NT-MDT palette format",
              path: "scientific/nt_mdt/nt_mdt_pal.ksy",
            }
          ],
        },
        {
          name: "spectroscopy",
          children: [
            {
              name: "avantes_roh60",
              title: "Avantes USB spectrometer ROH file 6.0",
              path: "scientific/spectroscopy/avantes_roh60.ksy",
            },
            {
              name: "specpr",
              title: "SPECtrum Processing Routines Data Format 3/4/88",
              path: "scientific/spectroscopy/specpr.ksy",
            }
          ],
        }
      ],
    },
    {
      name: "security",
      children: [
        {
          name: "efivar_signature_list",
          title: "UEFI Variable with Signature List",
          path: "security/efivar_signature_list.ksy",
        },
        {
          name: "openpgp_message",
          title: "OpenPGP message",
          path: "security/openpgp_message.ksy",
        },
        {
          name: "ssh_public_key",
          title: "SSH public key",
          path: "security/ssh_public_key.ksy",
        }
      ],
    },
    {
      name: "serialization",
      children: [
        {
          name: "bson",
          title: "bson",
          path: "serialization/bson.ksy",
        },
        {
          name: "chrome_pak",
          title: "Chrome PAK serialization format",
          path: "serialization/chrome_pak.ksy",
        },
        {
          name: "google_protobuf",
          title: "Google Protocol Buffers (protobuf)",
          path: "serialization/google_protobuf.ksy",
        },
        {
          name: "microsoft_cfb",
          title: "Microsoft Compound File Binary (CFB), AKA OLE (Object Linking and Embedding) file format",
          path: "serialization/microsoft_cfb.ksy",
        },
        {
          name: "msgpack",
          title: "MessagePack (msgpack) serialization format",
          path: "serialization/msgpack.ksy",
        },
        {
          name: "php_serialized_value",
          title: "Serialized PHP value",
          path: "serialization/php_serialized_value.ksy",
        },
        {
          name: "python_pickle",
          title: "Python pickle serialization format",
          path: "serialization/python_pickle.ksy",
        },
        {
          name: "ruby_marshal",
          title: "ruby_marshal",
          path: "serialization/ruby_marshal.ksy",
        },
        {
          name: "asn1",
          children: [
            {
              name: "asn1_der",
              title: "ASN.1 DER (Abstract Syntax Notation One, Distinguished Encoding Rules)",
              path: "serialization/asn1/asn1_der.ksy",
            }
          ],
        }
      ],
    },
    {
      name: "windows",
      children: [
        {
          name: "regf",
          title: "Windows registry database",
          path: "windows/regf.ksy",
        },
        {
          name: "windows_lnk_file",
          title: "Windows shell link file",
          path: "windows/windows_lnk_file.ksy",
        },
        {
          name: "windows_minidump",
          title: "Windows MiniDump",
          path: "windows/windows_minidump.ksy",
        },
        {
          name: "windows_resource_file",
          title: "Windows resource file",
          path: "windows/windows_resource_file.ksy",
        },
        {
          name: "windows_shell_items",
          title: "Windows Shell Items",
          path: "windows/windows_shell_items.ksy",
        },
        {
          name: "windows_systemtime",
          title: "Microsoft Windows SYSTEMTIME structure",
          path: "windows/windows_systemtime.ksy",
        }
      ],
    }
  ] as const satisfies ManifestEntry[];

/**
 * Helper type to extract template IDs from nested manifest structure
 */
type ExtractTemplateIds<T> = T extends readonly (infer U)[]
  ? U extends { name: string; title: string; path: string }
    ? U["name"]
    : U extends { name: string; children: infer C }
    ? ExtractTemplateIds<C>
    : never
  : never;

/**
 * Union type of all valid template ID strings
 */
export type TemplateId = ExtractTemplateIds<typeof manifest>;
