export const hexByteGap = 0 // Space between hex bytes
export const borderWidth = 1
export const addressPadding = 16
export const cellWidth = 30 // Fixed width of each hex cell
export const rowHeight = 24 // Fixed row height
export const asciiPadding = 16
export const addressHexGap = 16 // Gap between address and hex columns
export const hexAsciiGap = 16 // Gap between hex and ASCII columns
export const verticalPadding = 16 // Vertical padding for top and bottom rows
export const scrollbarWidth = 16 // Width of the scrollbar on the right side
